version: '2.0'

services:
  frontend:
    image: 'node:8'
    user: 'root'
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    links:
      - services:services
    ports:
      - '4200:4200'
    command: >
      bash -c " echo 'started and installing frontend...'
      && cd ./app
      && npm install -g @angular/cli
      && ng serve --host 0.0.0.0"

  services:
    image: 'node:8'
    user: 'root'
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    ports:
      - '8080:8888'
    command: >
      bash -c " echo 'started and installing services...'
      && cd ./app
      && npm start"
